name: add_2_calendar
description: A really simple Flutter plugin to add events to each platform's default calendar.
version: 2.2.4
homepage: https://github.com/ja2375/add_2_calendar

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.javih.add_2_calendar
        pluginClass: Add2CalendarPlugin
      ios:
        pluginClass: Add2CalendarPlugin
