name: add_2_calendar
description: A really simple Flutter plugin to add events to each platform's default calendar.
version: 3.0.0
homepage: https://github.com/ja2375/add_2_calendar

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.javih.add_2_calendar
        pluginClass: Add2CalendarPlugin
      ios:
        pluginClass: Add2CalendarPlugin
